### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by Lanzaa** [CS-Club-at-SJSU/CS-Club-Site-at-SJSU#13]
The current auto update script is terrible (too terrible to post online). It would be nice if there was a better update script that worked well with github's post receive url hooks. 

Maybe someone could write an update script in python for us to use? Comment on this issue for help.

**Comment by eblume** [comment]
To give a little background on this:

Github has 'Service Hooks' which allow actions to be performed every time there is a commit, tag, etc. Currently, we use a 'Post-Recieve URL hook' set to send a POST request to a URL. That URL belongs to an apache virtual host which then runs a script which fetches the updates to a local repository, checks them out, then pushes them to another directory (via rsync) to be served. The POST request also contains [a lot of information](http://help.github.com/post-receive-hooks/) but we aren't using any of it.

There is also a whole bunch of other commit hooks we can employ, but after looking at the list (which I can only seem to find by looking at a github project of which I am an admin on, sorry folks) it seems like the Post-Receive hooks are the way to go. One other option is to simply set up a cron job that fetches and re-deploys if there was a change, I guess it could even run once a minute since it's such a 'small' task - this might be easier but has the slightly frustrating side effect that changes won't show up immediately, which could confuse some members.

Personally, I would recommend writing a WSGI-Python application that recieves a POST request, validates that it is a [well-formed request from Github's servers](http://help.github.com/post-receive-hooks/), and then uses the `cgi` module to process the request info, and then take the appropriate deployment actions.

Question, Lanzaa - is the server that is serving our website the same server that is getting this POST request? It's OK if it's a different VHOST, just so long as it's the same filesystem. If not, we should use public-key ssh or rsync to push over the result of the deploy.

Also, consider using git's `archive` command to gather the files, so that git meta-data doesn't get copied over as well.

**Comment by Lanzaa** [comment]
The servers are different, so ssh passwordless public key authentication and rsync are being used to actually push the site. I can assist with anyone having problems with this part.

**Comment by Lanzaa** [comment]
We have moved the site to use github hosting. So auto-update is handled by github. Yay!
