### ISSUE TITLE
Framing issue for github plugin.

### ISSUE THREAD

**Issue by JPAdv-zz** [CS-Club-at-SJSU/CS-Club-Site-at-SJSU#17]
There seems to be an annoying alert every time I go to the club's website. When I click okay, it directs me to this markdott.github.com which does not exists.

**Comment by eblume** [comment]
Yeah that's the github fork button I think. Let's just remove it and replace it with a  better one - I chose that one initially because it tracked the number of forks, but I gather the guy deleted his repo - very nice of him to do that. :(

It shouldn't be hard to replace it with some other button that links to github's forking service, there is stuff all over the web for it.

**Comment by eblume** [comment]
Woops, didn't mean to close.

**Comment by Lanzaa** [comment]
The repo for the github button changed its url. Commit d3c8890 changes to the new url.

**Comment by Lanzaa** [comment]
As Erich said, we should think about replacing the button with something else. For now, the issue is fixed.

**Comment by eblume** [comment]
I'm still getting the issue - can anyone else confirm?

**Comment by Lanzaa** [comment]
Try force refreshing and clearing your cache. It seems ok to me. I would pull in the code for the buttons from [Markdotto's github buttons](https://github.com/markdotto/github-buttons) repo, but I'm not sure about the licensing issues.

**Comment by eblume** [comment]
Damnit Chrome, making me look all bad with your agressive cacheing.
